project_id = "dhoqhwkvzahvaapjcxtn"

[functions]
  [functions.check-trusted-device]
    verify_jwt = false
  [functions.get-all-profiles]
    verify_jwt = false
  [functions.register-trusted-device]
    verify_jwt = false
  [functions.update-user-balance]
    verify_jwt = false
